# Generated by Django 5.2 on 2025-04-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_remove_direccion_sucursal_remove_direccion_usuario'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direcciones.direccion'),
        ),
    ]
